import React, { useState, useEffect, useMemo } from 'react';
import { AppContext, type LangKey, type ThemeKey, type UserProfile, type UserAccount, type UserStats, type UserBadge, type Quest, type LevelRecord } from './appContextStore';
import { scheduleDailyReminders, sendImmediateTestNotification } from './lib/notifications';
import { clearQuestionHistory } from './lib/questionTracker';

const translations: Record<LangKey, Record<string, string>> = {
  en: {
    // Navigation
    home: "Learn",
    rank: "Leagues",
    profile: "Profile",
    settings: "Settings",
    quests: "Quests",

    // HUD Top Bar
    hearts: "Hearts",
    refillHearts: "Refill Hearts",
    fullHearts: "You have full hearts!",
    outOfHearts: "Out of Hearts! 💔",
    heartsRefillPrompt: "Practice a quick quiz to refill your hearts, or refill instantly with gems!",
    refillWithGems: "Refill 5 Hearts (20 💎)",
    notEnoughGems: "Not enough gems! Practice to earn more.",
    gems: "Gems",

    // Dashboard & Learning Journey
    unit1Title: "Unit 1: Foundations",
    unit1Subtitle: "Master India GK, World Events & Science Basics",
    guidebook: "Guidebook",
    guidebookModalTitle: "Unit 1 Guidebook",
    guidebookTips: "Key Concept Tips:\n• Pink City: Jaipur (Rajasthan)\n• Land of Five Rivers: Punjab\n• Highest Civilian Honor: Bharat Ratna\n• Powerhouse of Cell: Mitochondria",
    close: "Close",
    startLesson: "START",
    lockedLesson: "Complete previous lesson to unlock!",
    treasureChest: "Treasure Chest",
    chestUnlocked: "Chest Unlocked! +25 Gems & +30 XP! 🎉",
    chestClaimed: "Already Claimed",
    worldMapTitle: "Realm Quest Map",
    worldMapSubtitle: "Conquer levels, defeat realm bosses & collect stars",
    levelTitle: "Level {level}",
    starsEarned: "Stars Earned",
    starsTotal: "{stars} Stars",
    worldProgress: "World Progress",
    missionBriefing: "Mission Briefing",
    targetStars: "Earn up to 3 Stars",
    starGoal1: "⭐ 1 Star: 40%+ Accuracy",
    starGoal2: "⭐⭐ 2 Stars: 70%+ Accuracy",
    starGoal3: "⭐⭐⭐ 3 Stars: 90%+ Accuracy",
    launchMission: "LAUNCH LEVEL",
    lockedLevelMessage: "Complete Level {level} first to unlock this stage!",
    bossStage: "BOSS BATTLE",
    bossStageDesc: "Defeat the Realm Titan to advance!",
    chestClaimSuccess: "Chest Opened! +{gems} Gems & +{xp} XP! 🎉",
    nextLevelUnlocked: "Next Level Unlocked! 🚀",
    playNextLevel: "PLAY NEXT LEVEL",

    // AI & Practice
    aiDailyChallenge: "AI Daily Challenge",
    aiPracticeDesc: "Fresh questions on any topic generated by Gemini AI",
    startAiPractice: "Launch AI Practice",
    customTopic: "Custom Topic",
    enterTopicPlaceholder: "e.g. Space Exploration, Cricket, Modern History",
    generate: "Generate",
    dailyChallengeTitle: "Today's Daily Challenge",
    dailyChallengeDesc: "10 targeted questions to keep your streak alive & earn up to +100 XP!",
    categoriesTitle: "Quiz Categories",
    currentAffairsTitle: "Current Affairs & Trends",
    examPrepTitle: "Indian Competitive Exam Prep",
    generalGkTitle: "Core GK & General Realms",
    catCaIndiaTitle: "India Current Affairs",
    catCaIndiaDesc: "National News, Schemes, Summits, Awards & Defence",
    catCaWorldTitle: "World Current Affairs",
    catCaWorldDesc: "Global Summits, UN, Space, Bilateral Ties & Geopolitics",
    catSscCglTitle: "SSC CGL Exam",
    catSscCglDesc: "Polity, History, Economy, Science & Static GK",
    catSscChslTitle: "SSC CHSL Exam",
    catSscChslDesc: "10+2 Level Static GK, Science & Art",
    catUppscTitle: "UPPSC & State PCS",
    catUppscDesc: "UP Special GK, History, Polity & Budget",
    catUpscTitle: "UPSC Civil Services",
    catUpscDesc: "IAS/IPS Prelims GS: Polity, Environment & History",
    catRailwayTitle: "Railway RRB NTPC",
    catRailwayDesc: "Railway GK, Physics, Biology & Tech",
    catBankingTitle: "Banking & IBPS",
    catBankingDesc: "Banking Awareness, RBI Monetary Policy & Economy",
    allCategories: "All Categories",
    changeCategory: "Switch Category",
    levelMapForCategory: "{category} Level Map",
    catIndiaTitle: "India GK & Heritage",
    catIndiaDesc: "History, States, Culture & Geography",
    catWorldTitle: "World Geography",
    catWorldDesc: "Capitals, Oceans, Landmarks & Flags",
    catScienceTitle: "Science & Inventions",
    catScienceDesc: "Physics, Biology, Chem & Space",
    catMixTitle: "Mix Potpourri",
    catMixDesc: "Test yourself across all subjects",
    catAiTitle: "Gemini AI Custom Quiz",
    catAiDesc: "Generate 5 questions on any custom topic",
    startQuiz: "START QUIZ",
    playQuiz: "PLAY",
    viewPath: "Level Map",
    viewCategories: "Categories",
    welcomeGreeting: "Let's learn something new today!",

    // Quiz
    question: "Question",
    selectAnswer: "Choose your answer",
    didYouKnow: "💡 Did you know?",
    continueBtn: "CONTINUE",
    checkBtn: "CHECK",
    quizCompleted: "Lesson Complete! 🎉",
    xpEarned: "XP Earned",
    accuracy: "Accuracy",
    comboBonus: "Combo Bonus",
    returnHome: "CONTINUE TO PATH",
    tryAgain: "PRACTICE AGAIN",
    aiGenerating: "G-koo is consulting Gemini AI for questions...",
    lostAHeart: "Oops! -1 Heart 💔",
    offlineMode: "Offline Mode",
    offlineNotice: "No internet connection. Playing from offline question bank.",
    offlineBadge: "📡 Offline",
    offlineLevelLoaded: "📡 Offline Mode: Level questions loaded from offline bank.",
    youAreOffline: "You are currently offline",
    backOnline: "Back online! 🟢",

    // Bookmarks / Saved Questions
    savedQuestions: "Saved Questions",
    savedQuestionsTitle: "My Bookmarked Questions",
    savedQuestionsSubtitle: "Review & practice questions you saved during tests",
    bookmarkQuestion: "Bookmark Question",
    removeBookmark: "Remove Bookmark",
    questionSavedToast: "Question added to Bookmarks! ⭐",
    questionRemovedToast: "Removed from Bookmarks",
    practiceSavedQuestions: "Practice Saved Questions",
    noSavedQuestions: "No saved questions yet! Tap ⭐ during a quiz to save important questions.",
    clearAllSaved: "Clear All Saved",
    clearSavedConfirm: "Are you sure you want to clear all bookmarked questions?",
    totalSaved: "{count} Questions Saved",

    // Mistakes Review
    reviewMistakes: "Review Mistakes",
    mistakesNotebook: "Mistakes Notebook",
    mistakesSubtitle: "Analyze questions you missed & understand concepts",
    retestMistakes: "Practice Mistakes Only",
    flawlessNoMistakes: "Flawless Round! You made 0 mistakes! 🌟",
    yourAnswer: "Your Answer",
    correctAnswer: "Correct Answer",
    explanation: "Educational Fact",

    // Daily GK Flashcards
    dailyFlashcards: "Daily 1-Min GK Flashcards",
    dailyFactTitle: "Fact of the Day",
    tapToFlip: "Tap to Flip Card 🔄",
    factsExplored: "{count}/6 Daily Facts Read Today",

    // Exam Timer
    examTimer: "Exam Timer Mode",
    examTimerDesc: "Add a countdown timer to questions for real exam speed practice",
    timerSeconds: "{sec}s per question",
    timeUp: "Time's Up! ⏰",

    // Analytics
    subjectPerformance: "Subject Mastery & Weak Areas",
    subjectPerformanceDesc: "Real-time accuracy analytics based on your quiz attempts",
    strongSubjects: "Strong Subjects (80%+)",
    moderateSubjects: "Average (60-80%)",
    weakSubjects: "Needs Practice (<60%)",
    noAnalyticsYet: "Complete quizzes across different subjects to see your performance graph!",
    accuracyRate: "{rate}% Accuracy",
    practiceWeakArea: "Strengthen Now",

    // Daily Quests Modal
    dailyQuestsTitle: "Daily Quests",
    dailyQuestsSubtitle: "Complete quests daily to earn gems and unlock chests!",
    quest_earn_xp: "Earn 50 XP today",
    quest_finish_quiz: "Complete 2 practice lessons",
    quest_ai_quiz: "Solve 1 AI Daily Challenge",
    claimReward: "Claim",
    claimed: "Claimed",

    // Settings
    language: "Language",
    appearance: "Appearance",
    light: "Light",
    dark: "Dark",
    system: "System",
    preferences: "Preferences",
    soundFx: "Sound Effects",
    soundFxDesc: "Play cheerful audio feedback on answer choices",
    haptics: "Haptic Vibration",
    hapticsDesc: "Vibrate on quiz responses (mobile)",
    notificationsTitle: "Daily Study Reminders",
    notificationsDesc: "Get notified at 7:30 PM if you haven't played a quiz today to protect your streak",
    testNotification: "Send Test Notification",
    testNotificationSuccess: "Notification sent! Check your phone status bar 🔔",
    testNotificationDenied: "Please allow notifications in your phone/browser settings",
    geminiKeyTitle: "Google Gemini API Key (Optional)",
    geminiKeyDesc: "Add your key for unlimited real-time AI quiz questions. Leave empty to use built-in smart AI generator.",
    saveKey: "Save Key",
    apiKeySaved: "API Key saved successfully!",
    dangerZone: "Danger Zone",
    resetProgress: "Reset All Progress",
    resetConfirm: "Are you sure you want to reset your XP, streaks, and stats?",


    // Leaderboard
    leaderboardTitle: "League Standings",
    weeklySeason: "Season ends in 2d 18h",
    bronzeLeague: "Bronze League",
    silverLeague: "Silver League",
    goldLeague: "Gold League",
    diamondLeague: "Diamond League",
    topRankers: "Top Champions",
    promotionZone: "PROMOTION ZONE (Top 3)",
    yourRank: "Your Rank",
    allTime: "All Time",
    weekly: "Weekly League",

    // Profile
    profileTitle: "Player Profile",
    editName: "Edit Name",
    saveName: "Save",
    chooseAvatar: "Choose Avatar",
    memberSince: "Member since",
    statsOverview: "STATISTICS",
    quizzesCompletedLabel: "Lessons Finished",
    accuracyLabel: "Accuracy Rate",
    bestComboLabel: "Best Combo",
    level: "Level",
    nextLevelAt: "XP to next level",
    badgesTitle: "Badges & Achievements",
    badgeUnlocked: "Unlocked",
    badgeLocked: "Locked",
    signOut: "Sign Out",
    guestNote: "Playing locally. Sign in to save progress across devices!",
    guestModeBadge: "Guest Mode",
    signedInBadge: "Verified Member",

    // Auth & Accounts
    signIn: "Sign In",
    signUp: "Create Account",
    continueAsGuest: "Continue as Guest",
    welcomeBack: "Welcome back!",
    welcomeNewUser: "Join G-koo Today!",
    authSubtitleLogin: "Sign in to keep your streak and stats synchronized.",
    authSubtitleSignup: "Create your free account to track lessons and leaderboard rank.",
    fullName: "Full Name",
    namePlaceholder: "e.g. Sahil Khan",
    emailAddress: "Email Address",
    emailPlaceholder: "name@example.com",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    alreadyHaveAccount: "Already have an account? Sign In",
    dontHaveAccount: "Don't have an account? Create one",
    accountCreatedSuccess: "Account created successfully! 🎉",
    loginSuccess: "Welcome back! 🎉",
    invalidCredentials: "Invalid email or password",
    accountExists: "An account with this email already exists",
    fillAllFields: "Please fill in all required fields",
    logoutSuccess: "Switched to Guest Mode",
    guestAccount: "Guest Player",
    loggedInAs: "Logged in as",
    switchAccount: "Switch Account",
    signInToSync: "Sign In to Sync",
    syncProgressNote: "Sign in to save your XP & streaks permanently!",

    // Badges Data
    badge_first_step_title: "First Step",
    badge_first_step_desc: "Completed your first quiz challenge",
    badge_streak_3_title: "Flame Keeper",
    badge_streak_3_desc: "Maintained a 3-day active streak",
    badge_xp_500_title: "Century Club",
    badge_xp_500_desc: "Earned 500+ XP in total",
    badge_quiz_master_title: "Quiz Master",
    badge_quiz_master_desc: "Completed 10 or more quizzes successfully"
  },
  hi: {
    // Navigation
    home: "सीखें",
    rank: "लीग",
    profile: "प्रोफ़ाइल",
    settings: "सेटिंग्स",
    quests: "मिशन",

    // HUD Top Bar
    hearts: "हार्ट्स (Hearts)",
    refillHearts: "हार्ट्स रीफिल करें",
    fullHearts: "आपके पास पूरे 5 हार्ट्स हैं!",
    outOfHearts: "हार्ट्स खत्म हो गए! 💔",
    heartsRefillPrompt: "हार्ट्स वापस पाने के लिए अभ्यास क्विज खेलें, या जेम्स (💎) से तुरंत रीफिल करें!",
    refillWithGems: "5 हार्ट्स रीफिल करें (20 💎)",
    notEnoughGems: "पर्याप्त जेम्स नहीं हैं! अभ्यास करके जेम्स कमाएं।",
    gems: "जेम्स",

    // Dashboard & Learning Journey
    unit1Title: "यूनिट 1: मूलभूत ज्ञान",
    unit1Subtitle: "भारत सामान्य ज्ञान, विश्व घटनाएं एवं विज्ञान",
    guidebook: "गाइडबुक",
    guidebookModalTitle: "यूनिट 1 गाइडबुक",
    guidebookTips: "महत्वपूर्ण तथ्य:\n• गुलाबी नगर: जयपुर (राजस्थान)\n• पांच नदियों की भूमि: पंजाब\n• सर्वोच्च नागरिक सम्मान: भारत रत्न\n• कोशिका का पावरहाउस: माइटोकॉन्ड्रिया",
    close: "बंद करें",
    startLesson: "शुरू करें",
    lockedLesson: "अनलॉक करने के लिए पिछला पाठ पूरा करें!",
    treasureChest: "खज़ाना संदूक",
    chestUnlocked: "संदूक खुला! +25 जेम्स और +30 XP! 🎉",
    chestClaimed: "पहले से प्राप्त",
    worldMapTitle: "ज्ञान लोक मानचित्र",
    worldMapSubtitle: "स्तर पार करें, महा-बॉस हराएं और सितारे कमाएं",
    levelTitle: "स्तर {level}",
    starsEarned: "अर्जित सितारे",
    starsTotal: "{stars} सितारे",
    worldProgress: "लोक प्रगति",
    missionBriefing: "मिशन विवरण",
    targetStars: "3 सितारे तक प्राप्त करें",
    starGoal1: "⭐ 1 सितारा: 40%+ सटीकता",
    starGoal2: "⭐⭐ 2 सितारे: 70%+ सटीकता",
    starGoal3: "⭐⭐⭐ 3 सितारे: 90%+ सटीकता",
    launchMission: "स्तर शुरू करें",
    lockedLevelMessage: "इस स्तर को खोलने के लिए पहले स्तर {level} पूरा करें!",
    bossStage: "महा-बॉस मुकाबला",
    bossStageDesc: "आगे बढ़ने के लिए लोक के महा-बॉस को हराएं!",
    chestClaimSuccess: "खज़ाना खुला! +{gems} जेम्स और +{xp} XP! 🎉",
    nextLevelUnlocked: "अगला स्तर खुल गया! 🚀",
    playNextLevel: "अगला स्तर खेलें",

    // AI & Practice
    aiDailyChallenge: "AI दैनिक चुनौती",
    aiPracticeDesc: "Gemini AI द्वारा बनाए गए ताज़ा और नए सवाल",
    startAiPractice: "AI अभ्यास शुरू करें",
    customTopic: "कस्टम AI विषय",
    enterTopicPlaceholder: "उदा. अंतरिक्ष विज्ञान, क्रिकेट, भारत का इतिहास",
    generate: "क्विज बनाएं",
    dailyChallengeTitle: "आज की दैनिक चुनौती",
    dailyChallengeDesc: "अपनी स्ट्रीक बनाए रखने और अधिकतम +100 XP कमाने के लिए 10 प्रश्न!",
    categoriesTitle: "क्विज विषय",
    currentAffairsTitle: "समसामयिकी एवं करेंट अफेयर्स (Current Affairs)",
    examPrepTitle: "प्रतियोगी परीक्षा तैयारी (Govt Exams)",
    generalGkTitle: "सामान्य ज्ञान एवं विषय (Core GK)",
    catCaIndiaTitle: "भारत करेंट अफेयर्स (National CA)",
    catCaIndiaDesc: "राष्ट्रीय घटनाएं, सरकारी योजनाएं, सम्मेलन, पुरस्कार व रक्षा",
    catCaWorldTitle: "विश्व करेंट अफेयर्स (Global CA)",
    catCaWorldDesc: "वैश्विक सम्मेलन, अंतर्राष्ट्रीय संबंध, अंतरिक्ष व वैश्विक घटनाएं",
    catSscCglTitle: "एसएससी सीजीएल (SSC CGL)",
    catSscCglDesc: "संविधान, इतिहास, अर्थव्यवस्था, विज्ञान व सामान्य ज्ञान",
    catSscChslTitle: "एसएससी सीएचएसएल (SSC CHSL)",
    catSscChslDesc: "10+2 स्तर: स्टेटिक जीके, विज्ञान, कला व समसामयिकी",
    catUppscTitle: "यूपीपीएससी / राज्य पीसीएस (UPPSC)",
    catUppscDesc: "उत्तर प्रदेश विशेष ज्ञान, इतिहास, भूगोल व बजट",
    catUpscTitle: "यूपीएससी सिविल सेवा (IAS/IPS)",
    catUpscDesc: "आईएएस/आईपीएस प्रारंभिक परीक्षा: संविधान व पर्यावरण",
    catRailwayTitle: "रेलवे आरआरबी (RRB NTPC)",
    catRailwayDesc: "आरआरबी एनटीपीसी व ग्रुप डी: सामान्य विज्ञान व रेलवे ज्ञान",
    catBankingTitle: "बैंकिंग एवं आईबीपीएस (IBPS PO)",
    catBankingDesc: "बैंकिंग अवेयरनेस, मौद्रिक नीति, वित्तीय संस्थान व अर्थव्यवस्था",
    allCategories: "सभी विषय",
    changeCategory: "विषय बदलें",
    levelMapForCategory: "{category} स्तर मानचित्र",
    catIndiaTitle: "भारत ज्ञान एवं संस्कृति",
    catIndiaDesc: "इतिहास, राज्य, धरोहर और भूगोल",
    catWorldTitle: "विश्व भूगोल",
    catWorldDesc: "राजधानियां, महासागर, धरोहर एवं झंडे",
    catScienceTitle: "विज्ञान एवं खोजें",
    catScienceDesc: "भौतिकी, जीवविज्ञान, रसायन व अंतरिक्ष",
    catMixTitle: "मिश्रित चुनौती (Mix)",
    catMixDesc: "सभी विषयों की मिली-जुली परीक्षा",
    catAiTitle: "Gemini AI कस्टम क्विज",
    catAiDesc: "अपनी पसंद के किसी भी विषय पर 5 सवाल बनाएं",
    startQuiz: "क्विज खेलें",
    playQuiz: "शुरू करें",
    viewPath: "स्तर मानचित्र",
    viewCategories: "विषय (Categories)",
    welcomeGreeting: "चलिए आज कुछ नया और रोमांचक सीखते हैं!",

    // Quiz
    question: "प्रश्न",
    selectAnswer: "अपना उत्तर चुनें",
    didYouKnow: "💡 क्या आप जानते हैं?",
    continueBtn: "आगे बढ़ें",
    checkBtn: "जांचें",
    quizCompleted: "पाठ समाप्त! 🎉",
    xpEarned: "प्राप्त XP",
    accuracy: "सटीकता",
    comboBonus: "कॉम्बो बोनस",
    returnHome: "सफर पर लौटें",
    tryAgain: "पुनः अभ्यास करें",
    aiGenerating: "G-koo नए सवाल ला रहा है...",
    lostAHeart: "ओह! -1 हार्ट 💔",
    offlineMode: "ऑफलाइन मोड",
    offlineNotice: "इंटरनेट कनेक्ट नहीं है। ऑफलाइन प्रश्न बैंक से सवाल लोड किए गए हैं।",
    offlineBadge: "📡 ऑफलाइन",
    offlineLevelLoaded: "📡 ऑफलाइन मोड: लेवल के सवाल ऑफलाइन बैंक से तैयार किए गए हैं।",
    youAreOffline: "आप अभी ऑफलाइन हैं",
    backOnline: "आप वापस ऑनलाइन आ गए हैं! 🟢",

    // Bookmarks / Saved Questions
    savedQuestions: "बुकमार्क प्रश्न",
    savedQuestionsTitle: "मेरे सहेजे गए सवाल (Bookmarks)",
    savedQuestionsSubtitle: "क्विज के दौरान सहेजे गए महत्वपूर्ण सवालों का रिवीजन करें",
    bookmarkQuestion: "सवाल बुकमार्क करें",
    removeBookmark: "बुकमार्क हटाएं",
    questionSavedToast: "सवाल बुकमार्क में सहेजा गया! ⭐",
    questionRemovedToast: "बुकमार्क से हटा दिया गया",
    practiceSavedQuestions: "सहेजे गए सवालों का टेस्ट दें",
    noSavedQuestions: "अभी कोई सहेजा गया सवाल नहीं है! क्विज के दौरान ⭐ दबाकर सवाल सेव करें।",
    clearAllSaved: "सभी बुकमार्क हटाएं",
    clearSavedConfirm: "क्या आप सभी सहेजे गए सवाल हटाना चाहते हैं?",
    totalSaved: "{count} सवाल सहेजे गए",

    // Mistakes Review
    reviewMistakes: "गलतियां देखें (Review)",
    mistakesNotebook: "गलतियों की डायरी (Mistakes Notebook)",
    mistakesSubtitle: "गलत हुए सवालों का विश्लेषण करें और सही तथ्य समझें",
    retestMistakes: "सिर्फ गलत सवालों का री-टेस्ट दें",
    flawlessNoMistakes: "शानदार प्रदर्शन! आपने शून्य (0) गलतियां की हैं! 🌟",
    yourAnswer: "आपका उत्तर",
    correctAnswer: "सही उत्तर",
    explanation: "ज्ञानवर्धक तथ्य",

    // Daily GK Flashcards
    dailyFlashcards: "दैनिक 1-मिनट ज्ञान कार्ड्स (Flashcards)",
    dailyFactTitle: "आज का प्रमुख तथ्य",
    tapToFlip: "तथ्य देखने के लिए कार्ड छुएं 🔄",
    factsExplored: "आज {count}/6 ज्ञान कार्ड्स पढ़े गए",

    // Exam Timer
    examTimer: "एग्जाम टाइमर मोड (Timer Mode)",
    examTimerDesc: "असली परीक्षा जैसी स्पीड प्रैक्टिस के लिए हर सवाल पर टाइमर लगाएं",
    timerSeconds: "{sec} सेकंड प्रति सवाल",
    timeUp: "समय समाप्त! ⏰",

    // Analytics
    subjectPerformance: "विषय-वार मजबूती व कमजोरी रिपोर्ट",
    subjectPerformanceDesc: "आपके टेस्ट प्रयासों के आधार पर वास्तविक सटीकता विश्लेषण",
    strongSubjects: "मजबूत विषय (80%+ सटीकता)",
    moderateSubjects: "सामान्य (60-80%)",
    weakSubjects: "सुधार की आवश्यकता (<60%)",
    noAnalyticsYet: "अपना प्रदर्शन ग्राफ देखने के लिए अलग-अलग विषयों के क्विज हल करें!",
    accuracyRate: "{rate}% सटीकता",
    practiceWeakArea: "अभी मजबूत करें",

    // Daily Quests Modal
    dailyQuestsTitle: "दैनिक मिशन",
    dailyQuestsSubtitle: "रोज़ाना मिशन पूरे करके जेम्स और संदूक जीतें!",
    quest_earn_xp: "आज 50 XP अर्जित करें",
    quest_finish_quiz: "2 अभ्यास पाठ पूरे करें",
    quest_ai_quiz: "1 AI चुनौती हल करें",
    claimReward: "प्राप्त करें",
    claimed: "प्राप्त किया",

    // Settings
    language: "भाषा (Language)",
    appearance: "दिखावट (Theme)",
    light: "लाइट",
    dark: "डार्क",
    system: "सिस्टम",
    preferences: "प्राथमिकताएं",
    soundFx: "ध्वनि प्रभाव (Sound)",
    soundFxDesc: "उत्तर चुनने पर उत्साहवर्धक आवाज़ बजाएं",
    haptics: "वाइब्रेशन (Haptics)",
    hapticsDesc: "मोबाइल पर उत्तर देने पर हल्का कंपन",
    notificationsTitle: "दैनिक टेस्ट रिमाइंडर (Notifications)",
    notificationsDesc: "यदि आपने आज कोई टेस्ट नहीं दिया तो स्ट्रीक बचाने के लिए शाम 7:30 बजे रिमाइंडर पाएं",
    testNotification: "टेस्ट रिमाइंडर भेजें",
    testNotificationSuccess: "नोटिफिकेशन भेज दिया गया! अपना फोन नोटिफिकेशन बार देखें 🔔",
    testNotificationDenied: "कृपया फोन सेटिंग्स से नोटिफिकेशन की अनुमति प्रदान करें",
    geminiKeyTitle: "Google Gemini API Key (वैकल्पिक)",
    geminiKeyDesc: "असीमित AI प्रश्नों के लिए अपनी की डालें। खाली छोड़ने पर बिल्ट-इन स्मार्ट AI काम करेगा।",
    saveKey: "की सेव करें",
    apiKeySaved: "API Key सफलतापूर्वक सेव हो गई!",
    dangerZone: "डेटा रीसेट",
    resetProgress: "सारा डेटा रीसेट करें",
    resetConfirm: "क्या आप सच में अपनी XP, स्ट्रीक और आंकड़े रीसेट करना चाहते हैं?",


    // Leaderboard
    leaderboardTitle: "लीग रैंकिंग",
    weeklySeason: "सीज़न 2 दिन 18 घंटे में समाप्त होगा",
    bronzeLeague: "कांस्य (Bronze)",
    silverLeague: "रजत (Silver)",
    goldLeague: "स्वर्ण (Gold)",
    diamondLeague: "हीरा (Diamond)",
    topRankers: "शीर्ष विजेता",
    promotionZone: "पदोन्नति क्षेत्र (Top 3)",
    yourRank: "आपकी रैंक",
    allTime: "कुल समय",
    weekly: "साप्ताहिक लीग",

    // Profile
    profileTitle: "खिलाड़ी प्रोफ़ाइल",
    editName: "नाम बदलें",
    saveName: "सेव करें",
    chooseAvatar: "अवतार चुनें",
    memberSince: "सदस्यता",
    statsOverview: "आंकड़े और प्रगति",
    quizzesCompletedLabel: "हल किए गए पाठ",
    accuracyLabel: "सटीकता दर (Accuracy)",
    bestComboLabel: "सर्वश्रेष्ठ कॉम्बो",
    level: "स्तर (Level)",
    nextLevelAt: "अगले स्तर के लिए शेष XP",
    badgesTitle: "पदक और उपलब्धियां",
    badgeUnlocked: "अनलॉक",
    badgeLocked: "लॉक",
    signOut: "साइन आउट",
    guestNote: "लोकल गेस्ट प्लेयर। सभी डिवाइस पर सिंक करने के लिए साइन इन करें!",
    guestModeBadge: "अतिथि मोड",
    signedInBadge: "वेरिफाइड सदस्य",

    // Auth & Accounts
    signIn: "साइन इन (Sign In)",
    signUp: "नया खाता बनाएं (Sign Up)",
    continueAsGuest: "अतिथि (Guest) के रूप में जारी रखें",
    welcomeBack: "वापसी पर स्वागत है!",
    welcomeNewUser: "G-koo परिवार से जुड़ें!",
    authSubtitleLogin: "अपनी स्ट्रीक और प्रगति सुरक्षित रखने के लिए साइन इन करें।",
    authSubtitleSignup: "मुफ़्त खाता बनाएं और लीडरबोर्ड पर अपना नाम दर्ज करें।",
    fullName: "पूरा नाम",
    namePlaceholder: "उदा. राहुल शर्मा",
    emailAddress: "ईमेल पता",
    emailPlaceholder: "naam@example.com",
    password: "पासवर्ड (Password)",
    passwordPlaceholder: "अपना पासवर्ड डालें",
    alreadyHaveAccount: "पहले से खाता है? साइन इन करें",
    dontHaveAccount: "खाता नहीं है? नया बनाएं",
    accountCreatedSuccess: "खाता सफलतापूर्वक बन गया! 🎉",
    loginSuccess: "वापसी पर स्वागत है! 🎉",
    invalidCredentials: "गलत ईमेल या पासवर्ड",
    accountExists: "इस ईमेल से पहले से खाता मौजूद है",
    fillAllFields: "कृपया सभी आवश्यक जानकारी भरें",
    logoutSuccess: "अतिथि मोड में स्विच किया गया",
    guestAccount: "अतिथि खिलाड़ी",
    loggedInAs: "लॉग इन:",
    switchAccount: "खाता बदलें",
    signInToSync: "सिंक के लिए साइन इन करें",
    syncProgressNote: "अपनी XP और स्ट्रीक हमेशा सुरक्षित रखने के लिए साइन इन करें!",

    // Badges Data
    badge_first_step_title: "पहला कदम",
    badge_first_step_desc: "अपना पहला क्विज पूरा किया",
    badge_streak_3_title: "अग्नि रक्षक",
    badge_streak_3_desc: "3 दिनों की लगातार स्ट्रीक पूरी की",
    badge_xp_500_title: "500 क्लब",
    badge_xp_500_desc: "500 से अधिक XP अर्जित की",
    badge_quiz_master_title: "क्विज सम्राट",
    badge_quiz_master_desc: "10 या अधिक क्विज सफलतापूर्वक पूरे किए"
  }
};

const INITIAL_BADGES: UserBadge[] = [
  { id: 'first_step', titleKey: 'badge_first_step_title', descriptionKey: 'badge_first_step_desc', icon: '🎯', color: 'from-amber-400 to-orange-500', unlocked: false, requiredQuizzes: 1 },
  { id: 'streak_3', titleKey: 'badge_streak_3_title', descriptionKey: 'badge_streak_3_desc', icon: '🔥', color: 'from-[#FF5F6D] to-[#E64553]', unlocked: false, requiredStreak: 3 },
  { id: 'xp_500', titleKey: 'badge_xp_500_title', descriptionKey: 'badge_xp_500_desc', icon: '💎', color: 'from-blue-500 to-indigo-600', unlocked: false, requiredXp: 500 },
  { id: 'quiz_master', titleKey: 'badge_quiz_master_title', descriptionKey: 'badge_quiz_master_desc', icon: '👑', color: 'from-yellow-400 to-amber-600', unlocked: false, requiredQuizzes: 10 },
];

const DEFAULT_QUESTS: Quest[] = [
  { id: 'q_xp', titleKey: 'quest_earn_xp', target: 50, current: 0, rewardGems: 15, rewardXp: 20, completed: false, claimed: false },
  { id: 'q_quiz', titleKey: 'quest_finish_quiz', target: 2, current: 0, rewardGems: 20, rewardXp: 25, completed: false, claimed: false },
  { id: 'q_ai', titleKey: 'quest_ai_quiz', target: 1, current: 0, rewardGems: 25, rewardXp: 30, completed: false, claimed: false },
];

export const AppProvider = ({ children }: { children: React.ReactNode }) => {
  const [lang, setLang] = useState<LangKey>(() => (localStorage.getItem('lang') as LangKey) || 'en');
  const [theme, setTheme] = useState<ThemeKey>(() => (localStorage.getItem('theme') as ThemeKey) || 'system');
  
  // Real XP, Streak, Hearts, Gems
  const [xp, setXp] = useState<number>(() => parseInt(localStorage.getItem('xp') || '140', 10));
  const [streak, setStreak] = useState<number>(() => parseInt(localStorage.getItem('streak') || '3', 10));
  const [hearts, setHearts] = useState<number>(() => parseInt(localStorage.getItem('hearts') || '5', 10));
  const [gems, setGems] = useState<number>(() => parseInt(localStorage.getItem('gems') || '85', 10));

  // Audio, Haptics and Notifications settings
  const [soundEnabled, setSoundEnabled] = useState<boolean>(() => localStorage.getItem('soundEnabled') !== 'false');
  const [hapticsEnabled, setHapticsEnabled] = useState<boolean>(() => localStorage.getItem('hapticsEnabled') !== 'false');
  const [notificationsEnabled, setNotificationsEnabled] = useState<boolean>(() => localStorage.getItem('notificationsEnabled') !== 'false');

  // Gemini API Key
  const [geminiApiKey, setGeminiApiKey] = useState<string>(() => localStorage.getItem('geminiApiKey') || '');

  // Quests
  const [quests, setQuests] = useState<Quest[]>(() => {
    const saved = localStorage.getItem('userQuests');
    if (saved) {
      try { return JSON.parse(saved); } catch (e) { /* ignore */ }
    }
    return DEFAULT_QUESTS;
  });

  // User Profile
  const [profile, setProfile] = useState<UserProfile>(() => {
    const activeId = localStorage.getItem('gkoo_current_user_id');
    const savedAccounts = localStorage.getItem('gkoo_accounts');
    if (activeId && savedAccounts) {
      try {
        const parsed = JSON.parse(savedAccounts);
        if (parsed[activeId]) {
          return {
            name: parsed[activeId].name,
            avatar: parsed[activeId].avatar || '🦉',
            joinedDate: parsed[activeId].joinedDate || '2026'
          };
        }
      } catch (e) {}
    }
    const saved = localStorage.getItem('userProfile');
    if (saved) {
      try {
        const parsed = JSON.parse(saved);
        if (parsed.name && parsed.name !== 'Rahul Sharma') return parsed;
      } catch (e) { /* ignore */ }
    }
    return {
      name: 'Guest Scholar',
      avatar: '🦉',
      joinedDate: '2026'
    };
  });

  // User Stats
  const [stats, setStats] = useState<UserStats>(() => {
    const saved = localStorage.getItem('userStats');
    if (saved) {
      try { return JSON.parse(saved); } catch (e) { /* ignore */ }
    }
    return {
      quizzesCompleted: 4,
      totalAnswered: 20,
      correctAnswers: 18,
      bestCombo: 5
    };
  });

  // Accounts & Authentication
  const [accounts, setAccounts] = useState<Record<string, UserAccount>>(() => {
    const saved = localStorage.getItem('gkoo_accounts');
    if (saved) {
      try { return JSON.parse(saved); } catch (e) { /* ignore */ }
    }
    return {};
  });

  const [currentUserId, setCurrentUserId] = useState<string | null>(() => {
    return localStorage.getItem('gkoo_current_user_id') || null;
  });

  // Online / Offline Network Status Detection
  const [isOnline, setIsOnline] = useState<boolean>(() => 
    typeof navigator !== 'undefined' ? navigator.onLine : true
  );

  useEffect(() => {
    const handleOnline = () => setIsOnline(true);
    const handleOffline = () => setIsOnline(false);

    window.addEventListener('online', handleOnline);
    window.addEventListener('offline', handleOffline);

    return () => {
      window.removeEventListener('online', handleOnline);
      window.removeEventListener('offline', handleOffline);
    };
  }, []);

  // 1. Bookmarks / Saved Questions
  const [bookmarks, setBookmarks] = useState<import('./appContextStore').BookmarkedQuestion[]>(() => {
    const saved = localStorage.getItem('gkoo_bookmarks');
    if (saved) {
      try { return JSON.parse(saved); } catch (e) { /* ignore */ }
    }
    return [];
  });

  useEffect(() => {
    localStorage.setItem('gkoo_bookmarks', JSON.stringify(bookmarks));
  }, [bookmarks]);

  const toggleBookmark = (question: { id: number | string; text: string; options: string[]; answer: string; explanation?: string; category?: string }): boolean => {
    const norm = question.text.trim().toLowerCase();
    const exists = bookmarks.some(b => b.text.trim().toLowerCase() === norm);
    if (exists) {
      setBookmarks(prev => prev.filter(b => b.text.trim().toLowerCase() !== norm));
      return false;
    } else {
      const newBookmark: import('./appContextStore').BookmarkedQuestion = {
        ...question,
        id: question.id || `bm-${Date.now()}`,
        savedAt: Date.now(),
      };
      setBookmarks(prev => [newBookmark, ...prev]);
      return true;
    }
  };

  const isBookmarked = (questionText: string): boolean => {
    const norm = questionText.trim().toLowerCase();
    return bookmarks.some(b => b.text.trim().toLowerCase() === norm);
  };

  const removeBookmark = (id: number | string) => {
    setBookmarks(prev => prev.filter(b => b.id !== id));
  };

  const clearAllBookmarks = () => {
    setBookmarks([]);
  };

  // 2. Exam Timer Mode
  const [examTimerEnabled, setExamTimerEnabled] = useState<boolean>(() => {
    return localStorage.getItem('gkoo_exam_timer_enabled') === 'true';
  });

  const [examTimerSeconds, setExamTimerSeconds] = useState<number>(() => {
    const saved = localStorage.getItem('gkoo_exam_timer_seconds');
    return saved ? parseInt(saved, 10) : 20;
  });

  useEffect(() => {
    localStorage.setItem('gkoo_exam_timer_enabled', examTimerEnabled ? 'true' : 'false');
  }, [examTimerEnabled]);

  useEffect(() => {
    localStorage.setItem('gkoo_exam_timer_seconds', examTimerSeconds.toString());
  }, [examTimerSeconds]);

  // 3. Subject-wise Accuracy Stats
  const [categoryStats, setCategoryStats] = useState<Record<string, import('./appContextStore').CategoryAccuracyStat>>(() => {
    const saved = localStorage.getItem('gkoo_category_stats');
    if (saved) {
      try { return JSON.parse(saved); } catch (e) { /* ignore */ }
    }
    return {
      india: { totalAttempted: 15, totalCorrect: 13 },
      world: { totalAttempted: 10, totalCorrect: 8 },
      subjects: { totalAttempted: 12, totalCorrect: 10 },
      mix: { totalAttempted: 15, totalCorrect: 12 }
    };
  });

  useEffect(() => {
    localStorage.setItem('gkoo_category_stats', JSON.stringify(categoryStats));
  }, [categoryStats]);

  const recordCategoryAnswers = (categoryId: string, attempted: number, correct: number) => {
    if (!categoryId) return;
    const cleanId = categoryId.toLowerCase();
    setCategoryStats(prev => {
      const current = prev[cleanId] || { totalAttempted: 0, totalCorrect: 0 };
      return {
        ...prev,
        [cleanId]: {
          totalAttempted: current.totalAttempted + attempted,
          totalCorrect: current.totalCorrect + correct,
        }
      };
    });
  };

  const [isAuthModalOpen, setIsAuthModalOpen] = useState<boolean>(false);

  // Level-by-Level Progression State
  const [levelProgress, setLevelProgress] = useState<Record<number, LevelRecord>>(() => {
    const saved = localStorage.getItem('gkoo_level_progress');
    if (saved) {
      try {
        return JSON.parse(saved);
      } catch (e) { /* ignore */ }
    }
    return {
      1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 }
    };
  });

  const [claimedChests, setClaimedChests] = useState<Record<string, boolean>>(() => {
    const saved = localStorage.getItem('gkoo_claimed_chests');
    if (saved) {
      try { return JSON.parse(saved); } catch (e) { /* ignore */ }
    }
    return {};
  });

  // Sync Level Progress & Chests
  useEffect(() => {
    localStorage.setItem('gkoo_level_progress', JSON.stringify(levelProgress));
  }, [levelProgress]);

  useEffect(() => {
    localStorage.setItem('gkoo_claimed_chests', JSON.stringify(claimedChests));
  }, [claimedChests]);

  const maxUnlockedLevel = useMemo(() => {
    let maxUnlocked = 1;
    Object.entries(levelProgress).forEach(([lvlStr, data]) => {
      const lvl = parseInt(lvlStr, 10);
      if (data.completed && lvl + 1 > maxUnlocked) {
        maxUnlocked = lvl + 1;
      }
    });
    return maxUnlocked;
  }, [levelProgress]);

  const totalStars = useMemo(() => {
    return Object.values(levelProgress).reduce((acc, curr) => acc + (curr.stars || 0), 0);
  }, [levelProgress]);

  const completeLevel = (levelNum: number, accuracy: number, score: number) => {
    let starsEarned = 1;
    if (accuracy >= 90) starsEarned = 3;
    else if (accuracy >= 65) starsEarned = 2;
    else if (accuracy > 0) starsEarned = 1;

    setLevelProgress(prev => {
      const existing = prev[levelNum] || { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 };
      const updatedStars = Math.max(existing.stars || 0, starsEarned);
      const updatedAccuracy = Math.max(existing.highAccuracy || 0, accuracy);
      const updatedScore = Math.max(existing.bestScore || 0, score);

      const nextLevelNum = levelNum + 1;
      const nextLevelData = prev[nextLevelNum] || { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 };

      return {
        ...prev,
        [levelNum]: {
          completed: true,
          stars: updatedStars,
          highAccuracy: updatedAccuracy,
          bestScore: updatedScore
        },
        [nextLevelNum]: nextLevelData
      };
    });

    return { starsEarned, nextUnlocked: levelNum + 1 };
  };

  // Category-specific Level Progression State
  const [activeCategory, setActiveCategory] = useState<string>(() => localStorage.getItem('gkoo_active_category') || 'ssc_cgl');
  
  const [categoryLevelProgress, setCategoryLevelProgress] = useState<Record<string, Record<number, LevelRecord>>>(() => {
    const saved = localStorage.getItem('gkoo_cat_level_progress');
    if (saved) {
      try { return JSON.parse(saved); } catch (e) { /* ignore */ }
    }
    return {
      ssc_cgl: { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } },
      ssc_chsl: { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } },
      uppsc: { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } },
      upsc: { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } },
      railway: { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } },
      banking: { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } },
      india: { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } },
      world: { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } },
      subjects: { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } },
      mix: { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } },
    };
  });

  useEffect(() => {
    localStorage.setItem('gkoo_active_category', activeCategory);
  }, [activeCategory]);

  useEffect(() => {
    localStorage.setItem('gkoo_cat_level_progress', JSON.stringify(categoryLevelProgress));
  }, [categoryLevelProgress]);

  const getCategoryMaxUnlocked = (catId: string): number => {
    const catData = categoryLevelProgress[catId] || { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } };
    let maxUnlocked = 1;
    Object.entries(catData).forEach(([lvlStr, data]) => {
      const lvl = parseInt(lvlStr, 10);
      if (data.completed && lvl + 1 > maxUnlocked) {
        maxUnlocked = lvl + 1;
      }
    });
    return maxUnlocked;
  };

  const getCategoryTotalStars = (catId: string): number => {
    const catData = categoryLevelProgress[catId] || {};
    return Object.values(catData).reduce((acc, curr) => acc + (curr.stars || 0), 0);
  };

  const completeCategoryLevel = (catId: string, levelNum: number, accuracy: number, score: number) => {
    let starsEarned = 1;
    if (accuracy >= 90) starsEarned = 3;
    else if (accuracy >= 65) starsEarned = 2;
    else if (accuracy > 0) starsEarned = 1;

    setCategoryLevelProgress(prev => {
      const catData = prev[catId] || { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } };
      const existing = catData[levelNum] || { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 };
      const updatedStars = Math.max(existing.stars || 0, starsEarned);
      const updatedAccuracy = Math.max(existing.highAccuracy || 0, accuracy);
      const updatedScore = Math.max(existing.bestScore || 0, score);

      const nextLevelNum = levelNum + 1;
      const nextLevelData = catData[nextLevelNum] || { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 };

      return {
        ...prev,
        [catId]: {
          ...catData,
          [levelNum]: {
            completed: true,
            stars: updatedStars,
            highAccuracy: updatedAccuracy,
            bestScore: updatedScore
          },
          [nextLevelNum]: nextLevelData
        }
      };
    });

    if (catId === 'india' || !catId) {
      completeLevel(levelNum, accuracy, score);
    }

    return { starsEarned, nextUnlocked: levelNum + 1 };
  };

  const claimChest = (chestId: string, chestGems: number, chestXp: number) => {
    if (claimedChests[chestId]) return;
    setClaimedChests(prev => ({ ...prev, [chestId]: true }));
    addGems(chestGems);
    addXp(chestXp);
  };

  const currentUser = useMemo<UserAccount | null>(() => {
    if (!currentUserId || !accounts[currentUserId]) return null;
    return accounts[currentUserId];
  }, [currentUserId, accounts]);

  const isGuest = !currentUser || !!currentUser.isGuest;

  // Sync state with LocalStorage
  useEffect(() => { localStorage.setItem('lang', lang); }, [lang]);
  useEffect(() => { localStorage.setItem('xp', xp.toString()); }, [xp]);
  useEffect(() => { localStorage.setItem('streak', streak.toString()); }, [streak]);
  useEffect(() => { localStorage.setItem('hearts', hearts.toString()); }, [hearts]);
  useEffect(() => { localStorage.setItem('gems', gems.toString()); }, [gems]);
  useEffect(() => { localStorage.setItem('userQuests', JSON.stringify(quests)); }, [quests]);
  useEffect(() => { localStorage.setItem('soundEnabled', String(soundEnabled)); }, [soundEnabled]);
  useEffect(() => { localStorage.setItem('hapticsEnabled', String(hapticsEnabled)); }, [hapticsEnabled]);
  useEffect(() => { localStorage.setItem('notificationsEnabled', String(notificationsEnabled)); }, [notificationsEnabled]);
  useEffect(() => { localStorage.setItem('geminiApiKey', geminiApiKey); }, [geminiApiKey]);
  useEffect(() => { localStorage.setItem('userProfile', JSON.stringify(profile)); }, [profile]);

  // Schedule daily notification reminders
  useEffect(() => {
    scheduleDailyReminders(streak, lang, notificationsEnabled);
  }, [streak, lang, notificationsEnabled]);

  const triggerTestNotification = async (): Promise<boolean> => {
    return await sendImmediateTestNotification(streak, lang);
  };

  useEffect(() => { localStorage.setItem('userStats', JSON.stringify(stats)); }, [stats]);
  useEffect(() => { localStorage.setItem('gkoo_accounts', JSON.stringify(accounts)); }, [accounts]);
  useEffect(() => {
    if (currentUserId) {
      localStorage.setItem('gkoo_current_user_id', currentUserId);
    } else {
      localStorage.removeItem('gkoo_current_user_id');
    }
  }, [currentUserId]);

  // When active user data changes, update accounts record
  useEffect(() => {
    if (currentUserId && accounts[currentUserId]) {
      setAccounts(prev => ({
        ...prev,
        [currentUserId]: {
          ...prev[currentUserId],
          name: profile.name,
          avatar: profile.avatar,
          xp,
          streak,
          gems,
          hearts,
          stats
        }
      }));
    }
  }, [profile.name, profile.avatar, xp, streak, gems, hearts, stats, currentUserId]);

  // Sync Theme
  useEffect(() => {
    const root = window.document.documentElement;
    if (theme === 'dark' || (theme === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
      root.classList.add('dark');
    } else {
      root.classList.remove('dark');
    }
    localStorage.setItem('theme', theme);
  }, [theme]);

  // Real Daily Streak Calculation
  useEffect(() => {
    const lastLogin = localStorage.getItem('lastLoginDate');
    const today = new Date().toDateString();

    if (lastLogin !== today) {
       if (lastLogin) {
          const lastDate = new Date(lastLogin);
          const todayDate = new Date();
          const diffTime = Math.abs(todayDate.getTime() - lastDate.getTime());
          const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24)); 

          if (diffDays === 1) {
             setStreak(prev => prev + 1);
          } else if (diffDays > 1) {
             setStreak(1);
          }
       } else {
          setStreak(1);
       }
       localStorage.setItem('lastLoginDate', today);
       // Reset daily hearts and quests on new day
       setHearts(5);
    }
  }, []);

  const addXp = (amount: number) => {
    setXp(prev => prev + amount);
    // Update daily XP quest
    setQuests(prev => prev.map(q => {
      if (q.id === 'q_xp') {
        const nextCur = Math.min(q.target, q.current + amount);
        return { ...q, current: nextCur, completed: nextCur >= q.target };
      }
      return q;
    }));
  };

  const addGems = (amount: number) => {
    setGems(prev => prev + amount);
  };

  const spendHeart = (): boolean => {
    if (hearts > 0) {
      setHearts(prev => Math.max(0, prev - 1));
      return true;
    }
    return false;
  };

  const refillHearts = () => {
    setHearts(5);
  };

  const claimQuest = (questId: string) => {
    setQuests(prev => prev.map(q => {
      if (q.id === questId && q.completed && !q.claimed) {
        addGems(q.rewardGems);
        addXp(q.rewardXp);
        return { ...q, claimed: true };
      }
      return q;
    }));
  };

  const updateProfile = (updates: Partial<UserProfile>) => {
    setProfile(prev => ({ ...prev, ...updates }));
  };

  const recordQuizResult = (answered: number, correct: number, combo: number, gemsEarned = 15) => {
    // 1. Award Gems directly on quiz completion
    if (gemsEarned > 0) {
      setGems(prev => {
        const nextGems = prev + gemsEarned;
        localStorage.setItem('gems', nextGems.toString());
        return nextGems;
      });
    }

    // 2. Real Streak Tracking on Quiz Completion
    const today = new Date().toDateString();
    const lastActive = localStorage.getItem('gkoo_last_quiz_completed_date');
    if (lastActive !== today) {
      localStorage.setItem('gkoo_last_quiz_completed_date', today);
      setStreak(prev => {
        const nextStreak = prev > 0 ? prev + 1 : 1;
        localStorage.setItem('streak', nextStreak.toString());
        return nextStreak;
      });
    }

    // 3. Update User Stats
    setStats(prev => {
      const updated = {
        quizzesCompleted: prev.quizzesCompleted + 1,
        totalAnswered: prev.totalAnswered + answered,
        correctAnswers: prev.correctAnswers + correct,
        bestCombo: Math.max(prev.bestCombo, combo)
      };
      localStorage.setItem('userStats', JSON.stringify(updated));
      return updated;
    });

    // 4. Update Quest Progress
    setQuests(prev => {
      const updated = prev.map(q => {
        if (q.id === 'q_quiz') {
          const nextCur = Math.min(q.target, q.current + 1);
          return { ...q, current: nextCur, completed: nextCur >= q.target };
        }
        return q;
      });
      localStorage.setItem('userQuests', JSON.stringify(updated));
      return updated;
    });
  };

  const signUp = (name: string, email: string, password = '', avatar = '🦉') => {
    const trimmedEmail = email.trim().toLowerCase();
    const trimmedName = name.trim();

    if (!trimmedEmail || !trimmedName) {
      return { success: false, message: t('fillAllFields') };
    }

    // Check if email already registered
    const existing = Object.values(accounts).find(a => a.email.toLowerCase() === trimmedEmail);
    if (existing) {
      return { success: false, message: t('accountExists') };
    }

    const newId = `user_${Date.now()}`;
    const newAccount: UserAccount = {
      id: newId,
      name: trimmedName,
      email: trimmedEmail,
      password: password.trim(),
      avatar: avatar || '🦉',
      joinedDate: new Intl.DateTimeFormat('en-US', { month: 'short', year: 'numeric' }).format(new Date()),
      xp: xp > 0 ? xp : 140,
      streak: streak > 0 ? streak : 1,
      gems: gems > 0 ? gems : 85,
      hearts: 5,
      stats: { ...stats },
      isGuest: false,
    };

    setAccounts(prev => ({ ...prev, [newId]: newAccount }));
    setCurrentUserId(newId);
    setProfile({
      name: newAccount.name,
      avatar: newAccount.avatar,
      joinedDate: newAccount.joinedDate
    });

    return { success: true, message: t('accountCreatedSuccess') };
  };

  const signIn = (email: string, password = '') => {
    const trimmedEmail = email.trim().toLowerCase();
    if (!trimmedEmail) {
      return { success: false, message: t('fillAllFields') };
    }

    const account = Object.values(accounts).find(
      a => a.email.toLowerCase() === trimmedEmail && (!a.password || a.password === password.trim())
    );

    if (!account) {
      return { success: false, message: t('invalidCredentials') };
    }

    setCurrentUserId(account.id);
    setProfile({
      name: account.name,
      avatar: account.avatar,
      joinedDate: account.joinedDate
    });
    setXp(account.xp);
    setStreak(account.streak);
    setGems(account.gems);
    setHearts(account.hearts || 5);
    setStats(account.stats || { quizzesCompleted: 0, totalAnswered: 0, correctAnswers: 0, bestCombo: 0 });

    return { success: true, message: t('loginSuccess') };
  };

  const signInWithGoogle = (googleProfile: { id?: string; name: string; email: string; avatar?: string }) => {
    const trimmedEmail = (googleProfile.email || '').trim().toLowerCase();
    const cleanName = (googleProfile.name || 'Google User').trim();
    const cleanAvatar = googleProfile.avatar || '🦉';

    if (!trimmedEmail) {
      return { success: false, message: 'Google email missing' };
    }

    const existing = Object.values(accounts).find(a => a.email.toLowerCase() === trimmedEmail);

    if (existing) {
      const updatedAccount: UserAccount = {
        ...existing,
        name: cleanName || existing.name,
        avatar: cleanAvatar || existing.avatar,
        isGuest: false,
      };

      setAccounts(prev => ({ ...prev, [existing.id]: updatedAccount }));
      setCurrentUserId(existing.id);
      setProfile({
        name: updatedAccount.name,
        avatar: updatedAccount.avatar,
        joinedDate: updatedAccount.joinedDate
      });
      setXp(existing.xp);
      setStreak(existing.streak);
      setGems(existing.gems);
      setHearts(existing.hearts || 5);
      setStats(existing.stats || { quizzesCompleted: 0, totalAnswered: 0, correctAnswers: 0, bestCombo: 0 });

      return { success: true, message: t('loginSuccess') };
    }

    const newId = googleProfile.id || `google_${Date.now()}`;
    const newAccount: UserAccount = {
      id: newId,
      name: cleanName,
      email: trimmedEmail,
      avatar: cleanAvatar,
      joinedDate: new Intl.DateTimeFormat('en-US', { month: 'short', year: 'numeric' }).format(new Date()),
      xp: xp > 0 ? xp : 150,
      streak: streak > 0 ? streak : 1,
      gems: gems > 0 ? gems : 100,
      hearts: 5,
      stats: { ...stats },
      isGuest: false,
    };

    setAccounts(prev => ({ ...prev, [newId]: newAccount }));
    setCurrentUserId(newId);
    setProfile({
      name: newAccount.name,
      avatar: newAccount.avatar,
      joinedDate: newAccount.joinedDate
    });

    return { success: true, message: t('loginSuccess') };
  };

  const signOut = () => {
    setCurrentUserId(null);
    localStorage.removeItem('gkoo_current_user_id');
    setProfile({
      name: 'Guest Scholar',
      avatar: '🦉',
      joinedDate: '2026'
    });
  };

  const badges = useMemo<UserBadge[]>(() => {
    return INITIAL_BADGES.map(badge => {
      let isUnlocked = false;
      if (badge.requiredQuizzes && stats.quizzesCompleted >= badge.requiredQuizzes) isUnlocked = true;
      if (badge.requiredStreak && streak >= badge.requiredStreak) isUnlocked = true;
      if (badge.requiredXp && xp >= badge.requiredXp) isUnlocked = true;
      return { ...badge, unlocked: isUnlocked };
    });
  }, [stats.quizzesCompleted, streak, xp]);

  const resetAllProgress = () => {
    setXp(0);
    setStreak(1);
    setHearts(5);
    setGems(50);
    setStats({ quizzesCompleted: 0, totalAnswered: 0, correctAnswers: 0, bestCombo: 0 });
    setQuests(DEFAULT_QUESTS);
    setLevelProgress({ 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } });
    setCategoryLevelProgress({
      ca_india: { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } },
      ca_world: { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } },
      ssc_cgl: { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } },
      ssc_chsl: { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } },
      uppsc: { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } },
      upsc: { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } },
      railway: { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } },
      banking: { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } },
      india: { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } },
      world: { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } },
      subjects: { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } },
      mix: { 1: { completed: false, stars: 0, highAccuracy: 0, bestScore: 0 } },
    });
    setClaimedChests({});
    setBookmarks([]);
    setCategoryStats({});
    clearQuestionHistory();
    localStorage.removeItem('xp');
    localStorage.removeItem('streak');
    localStorage.removeItem('hearts');
    localStorage.removeItem('gems');
    localStorage.removeItem('userStats');
    localStorage.removeItem('userQuests');
    localStorage.removeItem('gkoo_level_progress');
    localStorage.removeItem('gkoo_cat_level_progress');
    localStorage.removeItem('gkoo_claimed_chests');
    localStorage.removeItem('gkoo_bookmarks');
    localStorage.removeItem('gkoo_category_stats');
    Object.keys(localStorage).forEach(k => {
      if (k.startsWith('gkoo_level_q_')) {
        localStorage.removeItem(k);
      }
    });
  };

  const t = (key: string, variables?: Record<string, string | number>) => {
    let text = translations[lang]?.[key] || translations.en?.[key] || key;
    if (variables) {
      Object.entries(variables).forEach(([k, v]) => {
        text = text.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v));
      });
    }
    return text;
  };

  return (
    <AppContext.Provider
      value={{
        lang,
        setLang,
        theme,
        setTheme,
        t,
        xp,
        streak,
        addXp,
        hearts,
        spendHeart,
        refillHearts,
        gems,
        addGems,
        quests,
        claimQuest,
        soundEnabled,
        setSoundEnabled,
        hapticsEnabled,
        setHapticsEnabled,
        notificationsEnabled,
        setNotificationsEnabled,
        triggerTestNotification,
        geminiApiKey,
        setGeminiApiKey,
        profile,
        updateProfile,
        stats,
        recordQuizResult,
        badges,
        resetAllProgress,
        currentUser,
        isGuest,
        isAuthModalOpen,
        setIsAuthModalOpen,
        signIn,
        signUp,
        signInWithGoogle,
        signOut,
        levelProgress,
        completeLevel,
        claimedChests,
        claimChest,
        totalStars,
        maxUnlockedLevel,
        activeCategory,
        setActiveCategory,
        categoryLevelProgress,
        getCategoryMaxUnlocked,
        getCategoryTotalStars,
        completeCategoryLevel,
        isOnline,
        // Bookmarks
        bookmarks,
        toggleBookmark,
        isBookmarked,
        removeBookmark,
        clearAllBookmarks,
        // Exam Timer
        examTimerEnabled,
        setExamTimerEnabled,
        examTimerSeconds,
        setExamTimerSeconds,
        // Category Performance Stats
        categoryStats,
        recordCategoryAnswers,
      }}

    >
      {children}
    </AppContext.Provider>
  );
};


